name: Prebuild

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive

            - name: Use Node.js 10.x
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '10'

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Build prebuilt binaries
              run: npm run prebuild
              env:
                  CI: true
                  GITHUB_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
